import type { ShopItem } from "./types";

export const shopItems: ShopItem[] = [
  /* ================= ОБЯЗАТЕЛЬНЫЕ РАСХОДЫ (Еда, здоровье, уход) ================= */
  {
    id: "food_bowl",
    name: "Сытный обед",
    type: "mandatory",
    price: 20,
    impact: { mood: 0, satiety: 30 },
    hint: "Ням-ням! Питомец сыт и полон сил 🥣",
    icon: "🥣",
    category: "Еда",
  },
  {
    id: "water",
    name: "Чистая водичка",
    type: "mandatory",
    price: 10,
    impact: { mood: 0, satiety: 15 },
    hint: "Свежая прохладная вода для бодрости 💧",
    icon: "💧",
    category: "Вода",
  },
  {
    id: "grooming",
    name: "Уход за шёрсткой",
    type: "mandatory",
    price: 25,
    impact: { mood: 10, satiety: 0 },
    hint: "Пенная ванна и мягкая расчёска 🧼",
    icon: "🧼",
    category: "Забота",
  },
  {
    id: "bed",
    name: "Уютная лежанка",
    type: "mandatory",
    price: 35,
    impact: { mood: 15, satiety: 0 },
    hint: "Мягкое облачко для сладких снов 🛏️",
    icon: "🛏️",
    category: "Уют",
  },
  {
    id: "vitamins",
    name: "Вкусные витаминки",
    type: "mandatory",
    price: 30,
    impact: { mood: 5, satiety: 10 },
    hint: "Сладкие ягодные витамины для лапок 💊",
    icon: "💊",
    category: "Здоровье",
  },
  {
    id: "vet_checkup",
    name: "Визит к Айболиту",
    type: "mandatory",
    price: 40,
    impact: { mood: 10, satiety: 10 },
    hint: "Добрый доктор послушает носик и животик 🩺",
    icon: "🩺",
    category: "Доктор",
  },

  /* ================= НЕОБЯЗАТЕЛЬНЫЕ РАСХОДЫ (Игры, радость, стиль) ================= */
  {
    id: "ball",
    name: "Звонкий мячик",
    type: "optional",
    price: 25,
    impact: { mood: 20, satiety: 0 },
    hint: "Прыг-скок! Мячик для весёлых догонялок ⚽",
    icon: "⚽",
    category: "Игрушки",
  },
  {
    id: "plush",
    name: "Плюшевый мишка",
    type: "optional",
    price: 45,
    impact: { mood: 25, satiety: 0 },
    hint: "Любимый друг для тёплых обнимашек 🧸",
    icon: "🧸",
    category: "Игрушки",
  },
  {
    id: "cape",
    name: "Плащ супергероя",
    type: "optional",
    price: 55,
    impact: { mood: 30, satiety: 0 },
    hint: "Развевается на ветру при беге! 🦸",
    icon: "🦸",
    category: "Наряды",
  },
  {
    id: "toy_house",
    name: "Игровой замок",
    type: "optional",
    price: 70,
    impact: { mood: 35, satiety: 0 },
    hint: "Сказочный домик с башенками для пряток 🏰",
    icon: "🏰",
    category: "Игры",
  },
  {
    id: "book",
    name: "Книга сказок",
    type: "optional",
    price: 35,
    impact: { mood: 20, satiety: 0 },
    hint: "Добрые истории с картинками на ночь 📖",
    icon: "📖",
    category: "Сказки",
  },
  {
    id: "glasses",
    name: "Солнечные очки",
    type: "optional",
    price: 30,
    impact: { mood: 15, satiety: 0 },
    hint: "Самый модный зверёк во дворе! 🕶️",
    icon: "🕶️",
    category: "Стиль",
  },
];